LM/urls.py
from django.conf.urls import url, include
from django.contrib.staticfiles import views
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('management.urls'))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.static.serve, {'document_root': settings.STATIC_ROOT}, name="static"),
        url(r'^media/(?P<path>.*)$', views.static.serve, {'document_root': settings.MEDIA_ROOT}, name="media")
    ]

management/urls.py
#coding:utf-8

from django.conf.urls import url
from management import views

urlpatterns = [
    url(r'^$', views.index, name='homepage'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^set_password/$', views.set_password, name='set_password'),
    url(r'^add_book/$', views.add_book, name='add_book'),
    url(r'^add_img/$', views.add_img, name='add_img'),
    url(r'^view_book_list/$', views.view_book_list, name='view_book_list'),
    url(r'^view_book/detail/$', views.detail, name='detail'),

    url(r'^join_club/(?P<uid>[0-9]+)$', views.join_club, name='join_club'),
    url(r'^user_show/(?P<id>[0-9]+)$', views.user_show, name='user_show'),
    url(r'^delete_user/(?P<userid>[0-9]+)$', views.delete_user, name='delete_user'),
    url(r'^change_club/(?P<id>[0-9]+)$', views.change_club, name='change_club'),

    url(r'^club_zixun_add$', views.club_zixun_add, name='club_zixun_add'),
    url(r'^club_zixun_insert$', views.club_zixun_insert, name='club_zixun_insert'),
    url(r'^show_act/$', views.show_act, name='show_act'),

    url(r'^show_act_detail/(?P<id>[0-9]+)$', views.show_act_detail, name='show_act_detail'),

    # 后台
    url(r'^myadmin/$', views.myadmin_index, name='myadmin_index'),
    url(r'^myadmin_reg/$', views.myadmin_reg, name='myadmin_reg'),
    url(r'^myadmin_usersinsert/$', views.myadmin_usersinsert, name='myadmin_usersinsert'),
    url(r'^myadmin_login/$', views.myadmin_login, name='myadmin_login'),
    url(r'^myadmin_dologin/$', views.myadmin_dologin, name='myadmin_dologin'),
    url(r'^myadmin_logout/$', views.myadmin_logout, name='myadmin_logout'),
    #浏览社团
    url(r'^myadmin_show_clubs/$', views.myadmin_show_clubs, name='myadmin_show_clubs'),
    url(r'^myadmin_club_info/(?P<id>[0-9]+)$', views.myadmin_club_info, name='myadmin_club_info'),
    #查看该社团成员
    url(r'show_members/(?P<id>[0-9]+)$', views.show_members, name='show_members'),
    url(r'del_member/(?P<id>[0-9]+)$', views.del_member, name='del_member'),
    # 更换社长
    url(r'^myadmin_change_member/(?P<id>[0-9]+)$', views.myadmin_change_member, name='myadmin_change_member'),
    url(r'^myadmin_weiren/(?P<id>[0-9]+)$', views.myadmin_weiren, name='myadmin_weiren'),
    #查看所有会员
    url(r'^myadmin_show_all_members/$', views.myadmin_show_all_members, name='myadmin_show_all_members'),
    #添加社团
    url(r'^myadmin_add_club/$', views.myadmin_add_club, name='myadmin_add_club'),

    url(r'^myadmin_insert_club/$', views.myadmin_insert_club, name='myadmin_insert_club'),

]

management/models.py
#coding:utf-8
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class MyUser(models.Model):
    user = models.OneToOneField(User)
    uid = models.IntegerField(max_length=11, default=0, verbose_name='所属社团')
    nickname = models.CharField(max_length=16, verbose_name='账号')
    permission = models.IntegerField(default=1, verbose_name='用户权限')
    user_state = models.IntegerField(default=1, verbose_name='状态')

    class Meta:
        db_table = 'management_myuser'
        verbose_name = '前台用户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.user.username



class Club(models.Model):
    name = models.CharField(max_length=128, verbose_name='社团名称')
    price = models.IntegerField(verbose_name='社团人数')
    author = models.CharField(max_length=128, verbose_name='社长')
    publish_date = models.DateField(verbose_name='社团成立日期')
    category = models.CharField(max_length=128, verbose_name='社团类别')
    detail = models.CharField(max_length=255, verbose_name='社团描述')

    class Meta:
        db_table = 'management_book'
        verbose_name = "社团"
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name



class Img(models.Model):
    name = models.CharField(max_length=128, verbose_name='图片名称')
    description = models.TextField(verbose_name='图片描述')
    img = models.ImageField(upload_to='image/%Y/%m/%d/', verbose_name='上传图片')
    book = models.ForeignKey(Club, verbose_name='所属社团')

    class META:
        db_table = 'management_img'
        verbose_name = '社团图片'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name



class club_zixun(models.Model):
    aid = models.IntegerField(default=0)
    activity_name = models.CharField(max_length=50, verbose_name='活动名称')
    activity_describe = models.CharField(max_length=200, verbose_name='活动描述')
    activity_person = models.IntegerField(verbose_name='活动人数')
    activity_img = models.CharField(max_length=255, verbose_name='活动图片')

    class Meta:
        db_table = 'club_zixun'
        verbose_name = '活动资讯'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.activity_name




# 后台管理员表
class Myadmin(models.Model):
    username = models.CharField(max_length=20, verbose_name='账号')
    password = models.CharField(max_length=20, verbose_name='密码')
    name = models.CharField(max_length=10, verbose_name='真实姓名')
    email = models.CharField(max_length=30, verbose_name='邮箱')

    class Meta:
        db_table = 'myadmin'
        verbose_name = '后台用户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

management/views.py
#coding:utf-8

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.models import User
from django.contrib import auth
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from management.models import MyUser, Club, Img, club_zixun, Myadmin
from django.core.urlresolvers import reverse
from management.utils import permission_check
import time,PIL,os
from PIL import Image

def index(request):
    user = request.user if request.user.is_authenticated() else None
    content = {
        'active_menu': 'homepage',
        'user': user,
    }
    return render(request, 'management/index.html', content)


def signup(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('homepage'))
    state = None
    if request.method == 'POST':
        password = request.POST.get('password', '')
        repeat_password = request.POST.get('repeat_password', '')
        if password == '' or repeat_password == '':
            state = 'empty'
        elif password != repeat_password:
            state = 'repeat_error'
        else:
            username = request.POST.get('username', '')
            if User.objects.filter(username=username):
                state = 'user_exist'
            else:
                new_user = User.objects.create_user(username=username, password=password,
                                                    email=request.POST.get('email', ''))
                new_user.save()
                new_my_user = MyUser(user=new_user, nickname=request.POST.get('nickname', ''))
                new_my_user.save()
                state = 'success'
    content = {
        'active_menu': 'homepage',
        'state': state,
        'user': None,
    }
    return render(request, 'management/signup.html', content)


def login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('homepage'))
    state = None
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('homepage'))
        else:
            state = 'not_exist_or_password_error'
    content = {
        'active_menu': 'homepage',
        'state': state,
        'user': None
    }
    return render(request, 'management/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('homepage'))


@login_required
def set_password(request):
    user = request.user
    state = None
    if request.method == 'POST':
        old_password = request.POST.get('old_password', '')
        new_password = request.POST.get('new_password', '')
        repeat_password = request.POST.get('repeat_password', '')
        if user.check_password(old_password):
            if not new_password:
                state = 'empty'
            elif new_password != repeat_password:
                state = 'repeat_error'
            else:
                user.set_password(new_password)
                user.save()
                state = 'success'
        else:
            state = 'password_error'
    content = {
        'user': user,
        'active_menu': 'homepage',
        'state': state,
    }
    return render(request, 'management/set_password.html', content)


@user_passes_test(permission_check)
def add_book(request):
    user = request.user
    state = None
    if request.method == 'POST':
        new_book = Club(
                name=request.POST.get('name', ''),
                detail=request.POST.get('detail', ''),
                author=request.POST.get('author', ''),
                category=request.POST.get('category', ''),
                price=request.POST.get('price', 0),
                publish_date=request.POST.get('publish_date', '')
        )
        new_book.save()
        state = 'success'
    content = {
        'user': user,
        'active_menu': 'add_book',
        'state': state,
    }
    return render(request, 'management/add_book.html', content)


def view_book_list(request):
    user = request.user if request.user.is_authenticated() else None
    # category_list = Club.objects.values_list('category', flat=True).distinct()
    # print(category_list)
    query_category = request.GET.get('category', 'all')
    if (not query_category) or Club.objects.filter(category=query_category).count() is 0:
        query_category = 'all'
        book_list = Club.objects.all()
        i = []
        for club in book_list:
            if club.category not in i:
                # print(club.category)
                i.append(club.category)
        category_list = i
    else:
        book_list = Club.objects.filter(category=query_category)
        i = []
        for club in book_list:
            if club.category not in i:
                # print(club.category)
                i.append(club.category)
        category_list = i

        # print(club.category)
        # book_list = Club.objects.filter(category=query_category)

    if request.method == 'POST':
        keyword = request.POST.get('keyword', '')
        book_list = Club.objects.filter(name__contains=keyword)
        print(book_list)
        query_category = 'all'

    paginator = Paginator(book_list, 5)
    page = request.GET.get('page')
    try:
        book_list = paginator.page(page)
    except PageNotAnInteger:
        book_list = paginator.page(1)
    except EmptyPage:
        book_list = paginator.page(paginator.num_pages)
    # print(category_list)
    content = {
        'user': user,
        'active_menu': 'view_book',
        'category_list': category_list,
        'query_category': query_category,
        'book_list': book_list,
    }
    return render(request, 'management/view_book_list.html', content)


def detail(request):
    user = request.user if request.user.is_authenticated() else None
    book_id = request.GET.get('id', '')
    if book_id == '':
        return HttpResponseRedirect(reverse('view_book_list'))
    try:
        book = Club.objects.get(pk=book_id)
#        need_user = MyUser.objects.get(user_id=user.id)
        content = {
            'user': user,
            'active_menu': 'view_book',
            'book': book,
        }
    except :
        return redirect(reverse('login'))
    return render(request, 'management/detail.html', content)


@user_passes_test(permission_check)
def add_img(request):
    user = request.user
    state = None
    if request.method == 'POST':
        try:
            new_img = Img(
                    name=request.POST.get('name', ''),
                    description=request.POST.get('description', ''),
                    img=request.FILES.get('img', ''),
                    book=Club.objects.get(pk=request.POST.get('book', ''))
            )
            new_img.save()
        except Club.DoesNotExist as e:
            state = 'error'
            print(e)
        else:
            state = 'success'
    content = {
        'user': user,
        'state': state,
        'book_list': Club.objects.all(),
        'active_menu': 'add_img',
    }
    return render(request, 'management/add_img.html', content)


def user_show(request, id):
    users = MyUser.objects.filter(uid=id)
    context = {'users': users}
    return render(request, 'management/user_show.html', context)

def join_club(request, uid):
    id = request.user.id
    # print(id)
    user = MyUser.objects.get(user_id=id)
    user.uid = uid
    user.save()
    return render(request, 'management/return.html')

def delete_user(request, userid):
    user = MyUser.objects.get(id=userid)
    user.uid = 0
    user.save()
    return render(request, 'management/delete_user.html')

def change_club(request, id):
    users = MyUser.objects.filter(uid=id)
    context = {'users': users}
    return render(request, 'management/change_club.html', context)

def club_zixun_add(request):
    return render(request, 'management/club_zixun_add.html')

def club_zixun_insert(request):
    try:
        # 判断并执行图片上传，缩放等处理
        myfile = request.FILES.get("pic", None)
        if not myfile:
            return HttpResponse("没有上传文件信息！")
        # 以时间戳命名一个新图片名称
        filename = str(time.time()) + "." + myfile.name.split('.').pop()
        path = os.path.join('./management/static/zixun/', filename)
        print(os.path.abspath(path))
        destination = open(path, 'wb+')
        for chunk in myfile.chunks():  # 分块写入文件
            destination.write(chunk)
        destination.close()
        # 执行图片缩放
        im = Image.open("./management/static/zixun/" + filename)
        im.thumbnail((400, 400))
        # 把缩放后的图像用jpeg格式保存:
        im.save("./management/static/zixun/_s" + filename, 'jpeg')
        # 缩放到220*220:
        im.thumbnail((220, 220))
        # 把缩放后的图像用jpeg格式保存:
        im.save("./management/static/zixun/_m" + filename, 'jpeg')


        ob = club_zixun()
        ob.activity_name = request.POST['activity_name']
        ob.activity_describe = request.POST['activity_describe']
        ob.activity_img = filename
        ob.activity_person = request.POST['activity_person']
        ob.save()
        context = {'info': '添加成功'}
        return render(request, 'management/myadmin/info.html', context)
    except Exception as e:
        print(e)
        context = {'info': '添加失败'}
        return render(request, 'management/myadmin/info.html', context)

def show_act(request):
    clubs = club_zixun.objects.all()
    context = {'clubs': clubs}
    return render(request, 'management/show_act.html', context)

def show_act_detail(request, id):
    club = club_zixun.objects.get(id=id)
    context = {'club': club}
    return render(request, 'management/show_act_detail.html', context)


# 后台

templates/management/add_book.html
{% extends "management/base.html" %}
{% load staticfiles %}
{% block title %}添加社团信息{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'success' %}
                    <div class="well">
                        <h2 class="text-success text-center">添加成功</h2>
                    </div>
                {% endif %}
                <form method="POST" role="form" class="form-horizontal">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">添加社团信息</h1>

                    <div class="form-group">
                        <label for="id_name" class="col-md-3 control-label">社团名称：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_name" required name="name" autofocus>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_detail" class="col-md-3 control-label">社团描述：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="detail" id="id_detail">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_author" class="col-md-3 control-label">社长：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="author" id="id_author">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_category" class="col-md-3 control-label">社团类型：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="category" id="id_category">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_price" class="col-md-3 control-label">社团规模：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="price" id="id_price">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_pubdate" class="col-md-3 control-label">社团成立日期：</label>
                        <div class="col-md-9">
                            <input type="date" class="form-control" required name="publish_date" id="id_pubdate">
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

templates/management/add_img.html
{% extends "management/base.html" %}
{% block title %}添加社团图片{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'success' %}
                    <div class="well">
                        <h2 class="text-success text-center">添加成功</h2>
                    </div>
                {% elif state == 'error' %}
                    <div class="well">
                        <h2 class="text-danger text-center">添加失败</h2>
                    </div>
                {% endif %}
                <form method="POST" role="form" class="form-horizontal" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">添加图片</h1>

                    <div class="form-group">
                        <label for="id_name" class="col-md-3 control-label">图片名称：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_name" required name="name" autofocus>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_description" class="col-md-3 control-label">图片描述：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="description" id="id_description">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_book" class="col-md-3 control-label">所属社团：</label>
                        <div class="col-md-9">
                            <select name="book" id="id_book" class="form-control">
                                {% for book in book_list %}
                                    <option value="{{ book.id }}">{{ book.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_img" class="col-md-3 control-label">上传图片：</label>
                        <div class="col-md-9">
                            <input type="file" id="id_img" name="img" class="form-control" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

templates/management/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!--[if lt IE 9]>
			<script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>
<body>
<!--Here is the navbar-->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#navbar-collapse-basepage">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'homepage' %}" class="navbar-brand">社团首页</a>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-basepage">
            <ul class="nav navbar-nav">
                {% if user.myuser.permission > 1 %}
                <li id="club_zixun_2"><a href="{% url 'show_act' %}">活动资讯</a></li>
                <li id="club_zixun"><a href="{% url 'club_zixun_add' %}">添加活动</a></li>
                {% else %}
                <li id="club_zixun_2"><a href="{% url 'show_act' %}">活动资讯</a></li>
                {% endif %}
                {% if user.myuser.permission > 1 %}
                    <li id="add_book"><a href="{% url 'add_book' %}">添加社团</a></li>
                    <li id="add_img"><a href="{% url 'add_img' %}">添加社团图片</a></li>
                    <li id="change_club"><a href="{% url 'change_club' user.myuser.uid %}">查看社团成员</a></li>
                {% endif %}
                <li id="view_book"><a href="{% url 'view_book_list' %}">查看社团</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user %}
                    <li><p class="navbar-text">欢迎你&nbsp;&nbsp;<span id="base_name">{{ user.myuser.nickname }}</span></p>
                    </li>
                    <li><a href="{% url 'logout' %}">注销</a></li>
                    <li><a href="{% url 'set_password' %}">修改密码</a></li>
                {% else %}
                    <li><a href="{% url 'signup' %}">注册</a></li>
                    <li><a href="{% url 'login' %}">登录</a></li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>
<!-- /nav -->
<!-- header -->
<header class="jumbotron subhead" id="header-base">
    <div class="container">
        <h1>社团管理系统</h1>
        <h3>&emsp;&emsp;Hello, Django!</h3>
    </div>
</header>
<!-- /.header -->
<!-- main part -->
{% block content %}{% endblock %}
<!-- /.main -->

<!-- footer -->
<footer class="footer" role="contentinfo">
    <hr>
    <div class="container">
        <p class="text-center"><strong>HIT-CS</strong></p>
        <p class="text-center">©All rights reserved</p>
        <h5 class="text-center"> Powered by&nbsp;<a href="">Silence</a></h5>
    </div>
</footer>
<!-- /.footer-->
<script type="text/javascript">
    $('#{{active_menu}}').addClass("active");
</script>
</body>
</html>

templates/management/detail.html
{% extends "management/base.html" %}
{% load staticfiles %}
{% block title %}查看社团{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="col-md-5">
                    {% if book.img_set.all %}
                        <div id="carousel-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                {% for img in book.img_set.all %}
                                    <li data-target="#carousel-generic" data-slide-to="{{ forloop.counter0 }}"
                                        {% if forloop.first %}class="active"{% endif %}></li>
                                {% endfor %}
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                {% for img in book.img_set.all %}
                                    <div {% if forloop.first %}class="item active"{% else %}class="item"{% endif %}>
                                        <img class="img-rounded" src="{% url 'media' img.img %}">
                                    </div>
                                {% endfor %}
                            </div>
                            <a class="left carousel-control" href="#carousel-generic" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-generic" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    {% else %}
                        <p class="text-center">暂无图片</p>
                    {% endif %}
                </div>
                <div class="col-md-6 col-md-offset-1">
                    <h2 class="text-center">{{ book.name }}</h2>
                    <br>
                    <h3>社团描述：{{ book.detail }}</h3>
                    <h3>社长：{{ book.author }}</h3>
                    <h3>社团类别：{{ book.category }}</h3>
                    <h3>社团成立日期：{{ book.publish_date|date:"Y-m-d" }}</h3>
                    <h3>社团规模(人)：{{ book.price }}</h3> <br>

                    {% if user.myuser.permission == 1 %}
                        <a href="{% url  'user_show' book.id %}">查看社团成员</a> <br> <br>
                        <a href="{% url 'join_club' book.id %}">点击此处加入社团</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/management/signup.html
{% extends "management/base.html" %}
{% load staticfiles %}
{% block title %}注册{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'success' %}
                    <div class="well">
                        <h2 class="text-success text-center">注册成功！</h2>
                    </div>
                {% elif state == 'repeat_error' %}
                    <div class="well">
                        <h2 class="text-warning text-center">密码重复错误</h2>
                    </div>
                {% elif state == 'empty' %}
                    <div class="well">
                        <h2 class="text-warning text-center">密码不能为空</h2>
                    </div>
                {% elif state == 'user_exist' %}
                    <div class="well">
                        <h2 class="text-danger text-center">用户已经存在</h2>
                    </div>
                {% endif %}
                <form method="POST" role="form" class="form-horizontal">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">请注册</h1>

                    <div class="form-group">
                        <label for="id_user_name" class="col-md-3 control-label">用户名：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_user_name" required name="username"
                                   autofocus>
                            <span class="help-block">用于登陆，可以包括大小写字母和下划线。</span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_name" class="col-md-3 control-label">姓名：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="nickname" id="id_name">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_passwd" class="col-md-3 control-label">密码：</label>
                        <div class="col-md-9">
                            <input type="password" class="form-control" required name="password" id="id_passwd">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_repasswd" class="col-md-3 control-label">重复密码：</label>
                        <div class="col-md-9">
                            <input type="password" class="form-control" required name="repeat_password"
                                   id="id_repasswd">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_email" class="col-md-3 control-label">电子邮件：</label>
                        <div class="col-md-9">
                            <input type="email" class="form-control" required name="email" id="id_email">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit" id="id_submit">注册</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

{% endblock %}